#
# service endpoint for keystone's db
#
apiVersion: v1
kind: Service
metadata:
  labels:
    name: keystone-db
  name: db
spec:
  ports:
    # The port that this service should serve on.
    - port: 3306
  # Label keys and values that must match in order to receive traffic for this service.
  selector:
    name: keystone-db
