#
# replication controller that sets up scalable keystone
#
apiVersion: v1
kind: ReplicationController
metadata:
  name: keystone-rc
spec:
  replicas: 3
  selector:
    name: keystone
  template:
    metadata:
      labels:
        name: keystone
    spec:
      containers:
        - image: bodepd/keystone
          name: keystone
          env:
            - name: MYSQL_USER
              value: keystone
            - name: MYSQL_PASSWORD
              value: keystone
            - name: MYSQL_DATABASE
              value: keystone
            - name: ADMIN_TOKEN
              value: token123
          ports:
            - containerPort: 5000
              name: keystone-public
              containerPort: 35357
              name: keystone-admin
          imagePullPolicy: Always
        - image: memcached
          name: memcached
          ports:
            - containerPort: 11211
              name: memcached
      # TODI properly understand what this does
      restartPolicy: Always
