apiVersion: v1
kind: Service
metadata:
  labels:
    name: keystone-public
  name: keystone-public
spec:
  type: LoadBalancer
  ports:
    # The port that this service should serve on.
    - port: 5000
      targetPort: 5000
      protocol: TCP
  # Label keys and values that must match in order to receive traffic for this service.
  selector:
    name: keystone
