apiVersion: v1
kind: Pod
metadata:
  name: keystone
  labels:
    name: keystone
spec:
  containers:
    - image: bodepd/keystone
      name: keystone
      env:
        - name: MYSQL_USER
          value: keystone
        - name: MYSQL_PASSWORD
          value: keystone
        - name: MYSQL_DATABASE
          value: keystone
      ports:
        - containerPort: 5000
          name: keystone-public
          containerPort: 35357
          name: keystone-admin
      imagePullPolicy: Always
