apiVersion: v1
kind: Pod
metadata:
  name: keystone-db
  labels:
    name: keystone-db
spec:
  containers:
    - resources:
        limits:
          cpu: 0.5
      image: mariadb
      name: keystone-db
      env:
        - name: MYSQL_USER
          value: keystone
        - name: MYSQL_PASSWORD
          value: keystone
        - name: MYSQL_DATABASE
          value: keystone
        - name: MYSQL_ROOT_PASSWORD
          value: yourpassword
      ports:
        - containerPort: 3306
          name: keystone-db
# I can deal with persistent volumes later
#      volumeMounts:
#          # This name must match the volumes.name below.
#        - name: mysql-persistent-storage
#          mountPath: /var/lib/mysql
#  volumes:
#    - name: mysql-persistent-storage
#      gcePersistentDisk:
#        # This disk must already exist.
#        pdName: mysql-disk
#        fsType: ext4
