# definition of keystone and memcache instance
# TODO this has been moved to the template of the
# keystone replication controller
apiVersion: v1
kind: Pod
metadata:
  name: keystone
  labels:
    name: keystone
spec:
  containers:
    - image: bodepd/keystone
      name: keystone
      env:
        - name: MYSQL_USER
          value: keystone
        - name: MYSQL_PASSWORD
          value: keystone
        - name: MYSQL_DATABASE
          value: keystone
        - name: ADMIN_TOKEN
          value: token123
      ports:
        - containerPort: 5000
          name: keystone-public
          containerPort: 35357
          name: keystone-admin
      imagePullPolicy: Always
    - image: memcached
      name: memcached
      ports:
        - containerPort: 11211
          name: memcached
