apiVersion: v1
kind: Service
metadata:
  labels:
    name: keystone-admin
  name: keystone-admin
spec:
  # can I have a private network load balancer?
  type: LoadBalancer
  ports:
    # The port that this service should serve on.
    - port: 35357
      targetPort: 35357
      protocol: TCP
  # Label keys and values that must match in order to receive traffic for this service.
  selector:
    name: keystone
